### ISSUE TITLE
Throw more helpful error on duplicate keys in config

### ISSUE THREAD

**Issue by silverwind** [stylelint/stylelint#2051]
Using stylelint 7.50. and a YAML config like:
```yaml
rules:
  selector-pseudo-element-colon-notation: single
  selector-pseudo-element-colon-notation: single
```
Running the CLI:
````
$ stylelint *.css
Error
    at generateError (/Users/silverwind/.npm-global/lib/node_modules/stylelint/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/Users/silverwind/.npm-global/lib/node_modules/stylelint/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at storeMappingPair (/Users/silverwind/.npm-global/lib/node_modules/stylelint/node_modules/js-yaml/lib/js-yaml/loader.js:305:7)
    at readBlockMapping (/Users/silverwind/.npm-global/lib/node_modules/stylelint/node_modules/js-yaml/lib/js-yaml/loader.js:1066:9)
    at composeNode (/Users/silverwind/.npm-global/lib/node_modules/stylelint/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
    at readBlockMapping (/Users/silverwind/.npm-global/lib/node_modules/stylelint/node_modules/js-yaml/lib/js-yaml/loader.js:1057:11)
    at composeNode (/Users/silverwind/.npm-global/lib/node_modules/stylelint/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
    at readDocument (/Users/silverwind/.npm-global/lib/node_modules/stylelint/node_modules/js-yaml/lib/js-yaml/loader.js:1489:3)
    at loadDocuments (/Users/silverwind/.npm-global/lib/node_modules/stylelint/node_modules/js-yaml/lib/js-yaml/loader.js:1545:5)
    at load (/Users/silverwind/.npm-global/lib/node_modules/stylelint/node_modules/js-yaml/lib/js-yaml/loader.js:1562:19)
````
It'd be great if the line with the duplicate key would be printed instead of the stack trace which really doesn't tell the user anything helpful to solve the issue.

**Comment by davidtheclark** [comment]
👍  Good idea.

**Comment by silverwind** [comment]
@davidtheclark a simple solution to the duplicate key problem in YAML would be enable the `json` option of [js-yaml](https://github.com/nodeca/js-yaml#safeload-string---options-) which overrides duplicate keys instead of throwing, just like `JSON.parse`. Do you think that's acceptable?

**Comment by silverwind** [comment]
https://github.com/davidtheclark/cosmiconfig/pull/37

**Comment by davidtheclark** [comment]
@silverwind I don't think the goal should be to not throw the error. I think the goal should be to have a more helpful error message. 

Duplicate keys is unquestionably a mistake, so should throw, I think.

**Comment by silverwind** [comment]
How about printing a warning when the config fails to parse without that option and parses with it? It's certainly an error, but not a critical one.

**Comment by silverwind** [comment]
On second thougth, it might be easier to just return a different error from `cosmiconfig`, but I'd argue that it should be done for JSON too, to be consistent. Will look into it.

**Comment by davidtheclark** [comment]
>  I'd argue that it should be done for JSON too, to be consistent

Agreed.

**Comment by silverwind** [comment]
I'm just not sure such a parser exists yet. I filed https://github.com/rlidwka/jju/issues/26.

**Comment by JaKXz** [comment]
Just curious if there are any updates on this? The issue [has surfaced here](https://github.com/vieron/stylelint-webpack-plugin/issues/40) and I tried going through `cosmiconfig` but the tests failed to run.

**Comment by JaKXz** [comment]
@davidtheclark correct me if I'm wrong, but this has been addressed in https://github.com/davidtheclark/cosmiconfig/commit/836a17c252a3392e628bf1c3c3947d31475195a1 right? 

I think what's remaining for `stylelint-webpack-plugin` is for the `.lint(options)` promise to reject with this error. Let me know what you think.

**Comment by davidtheclark** [comment]
@JaKXz I switched JSON-parsing modules but did not *intentionally* fix this issue. *Is* it fixed now? Want to submit a PR demonstrating so we don't regress in the future?

**Comment by silverwind** [comment]
It's not fixed. The YAML parser is strict by default while the JSON parser is lenient with no option to be strict.

**Comment by jeddy3** [comment]
Fixed:

```
jeddy3@MacBook stylelint-test % npx stylelint test.css
YAMLSemanticError: YAML Error in /Users/jeddy3/Projects/stylelint-test/.stylelintrc.yaml:
Map keys must be unique; "selector-pseudo-element-colon-notation" is repeated at line 2, column 3:

  selector-pseudo-element-colon-notation: single
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^…
```
