### ISSUE TITLE
Fix unfixed errors not being reported

### ISSUE THREAD

**Issue by guchongxi** [stylelint/stylelint#4289]
> Clearly describe the bug

when I was running `stylelint '**/*.scss'`, I got code error, like this

```shell
yarn run v1.10.1
$ stylelint '**/*.scss'

style/mixins.scss
 47:5  ✖  Expected "display" to come before "color" in group "Box Model"             order/properties-order
 50:5  ✖  Expected "overflow" to come before "line-height" in group "Box Model"      order/properties-order

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

when I was running `stylelint '**/*.scss' --fix`, there is no code error

```shell
yarn run v1.10.1
$ stylelint '**/*.scss' --fix
✨  Done in 4.87s.
```

I think the error has been fixed, but I check code, the error is not be fixed and there is no report for them

> What stylelint configuration is needed to reproduce the bug?

.stylelintrc.js

```js
module.exports = {
  extends: [
    'stylelint-config-standard',
    'stylelint-config-recommended-scss',
    'stylelint-config-rational-order',
    'stylelint-prettier/recommended',
  ],
  plugins: ['stylelint-scss', 'stylelint-declaration-block-no-ignored-properties'],
  rules: {
    'plugin/declaration-block-no-ignored-properties': true,
    'unit-no-unknown': [
      true,
      {
        ignoreUnits: ['rpx'],
      },
    ],
    'selector-type-no-unknown': [
      true,
      {
        ignoreTypes: ['radio', 'ec-canvas', 'rich-text', 'dxd-icon', 'page'],
      },
    ],
    'no-empty-source': null,
  },
};
```

> Which version of stylelint are you using?

`11.0.0`

> What did you expect to happen?

report all unfixed errors.

> What actually happened (e.g. what warnings or errors did you get)?

Unfixed errors NOT be reported.

**Comment by vankop** [comment]
Thanks for report, could you provide css that you are using?

**Comment by guchongxi** [comment]
Here is my code in test.scss

```scss
@mixin text-overflow($num, $line-height: 36) {
  @if $num==1 {
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
    word-break: break-all;
  } @else {
    color: #fff;
    display: -webkit-box;
    max-height: $line-height * $num + rpx;
    line-height: $line-height + rpx;
    overflow: hidden;
    word-break: break-all;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: $num;
  }
}
```

**Comment by hudochenkov** [comment]
What stylelint-order version do you use? This problem was fixed in [stylelint-order@3.0.1](https://github.com/hudochenkov/stylelint-order/releases/tag/3.0.1).

**Comment by jeddy3** [comment]
Hopefully resolved in stylelint-order@3.0.1.

Feel free to open a further issue in that [plugin's issue tracker](https://github.com/hudochenkov/stylelint-order/issues) if not.

**Comment by guchongxi** [comment]
Thank you for helping me.

But, It seems that this is not the plugin version problem.

My plugins version

```json
    "stylelint": "^11.0.0",
    "stylelint-config-prettier": "^5.2.0",
    "stylelint-config-rational-order": "^0.1.2",
    "stylelint-config-recommended-scss": "^3.3.0",
    "stylelint-config-standard": "^19.0.0",
    "stylelint-declaration-block-no-ignored-properties": "^2.1.0",
    "stylelint-order": "^3.1.1",
    "stylelint-prettier": "^1.1.1",
    "stylelint-scss": "^3.11.0"
```

**Comment by hudochenkov** [comment]
Please, create a minimum reproducible repository. Disable as much plugins as you can to still have issue reproduced.

**Comment by guchongxi** [comment]
Sorry to see it a little late.

please checkout [guchongxi/test-stylelint](https://github.com/guchongxi/test-stylelint) to reproduce the issues

**Comment by guchongxi** [comment]
Does anyone care about this?

**Comment by hudochenkov** [comment]
Problem with `stylelint-config-rational-order`. It mess up somehow (because it's not a real config, it's a plugin which tries to use `stylelint-order` internals).

When I change config to not use this config:

```js
module.exports = {
  plugins: [
    'stylelint-order'
  ],
  extends: [
    // 'stylelint-config-rational-order',
  ],
  rules: {
    'order/properties-order': [
      'display',
      'color',
      'overflow',
      'line-height'
    ]
  },
};
```

Stylesheet does not get fixed, but all violations are reported.
